In [1]:
import numpy as np

In [2]:
import numpy as np

# Create a square matrix
matrix = np.array([[1, 2, -1],
                  [1, 0, 1],
                  [0, 1, 0]])

# Calculate the inverse of the matrix
inverse_matrix = np.linalg.inv(matrix)

print("Original Matrix:")
print(matrix)
print("\nInverse Matrix:")
print(inverse_matrix)


Original Matrix:
[[ 1  2 -1]
 [ 1  0  1]
 [ 0  1  0]]

Inverse Matrix:
[[ 0.5  0.5 -1. ]
 [-0.  -0.   1. ]
 [-0.5  0.5  1. ]]


In [10]:
asdfsdf = np.array([[5, 2, 3],
                    [-1, -3, 2],
                    [0, 1, -1]])
fsdf = np.array([[1, 0, -4],
                 [2, 1, 0],
                 [8, -1, 0]])

aaaaa = np.matmul(asdfsdf, fsdf)
print(aaaaa)
np.linalg.det(aaaaa)

[[ 33  -1 -20]
 [  9  -5   4]
 [ -6   2   0]]


2.0783375020982994e-13

In [5]:
np.linalg.det(fsdf)

-2.0